/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::core::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub type __u8 = ::aya_ebpf::cty::c_uchar;
pub type __u16 = ::aya_ebpf::cty::c_ushort;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct trace_entry {
    pub type_: ::aya_ebpf::cty::c_ushort,
    pub flags: ::aya_ebpf::cty::c_uchar,
    pub preempt_count: ::aya_ebpf::cty::c_uchar,
    pub pid: ::aya_ebpf::cty::c_int,
}
#[repr(C)]
#[derive(Debug)]
pub struct trace_event_raw_inet_sock_set_state {
    pub ent: trace_entry,
    pub skaddr: *const ::aya_ebpf::cty::c_void,
    pub oldstate: ::aya_ebpf::cty::c_int,
    pub newstate: ::aya_ebpf::cty::c_int,
    pub sport: __u16,
    pub dport: __u16,
    pub family: __u16,
    pub protocol: __u16,
    pub saddr: [__u8; 4usize],
    pub daddr: [__u8; 4usize],
    pub saddr_v6: [__u8; 16usize],
    pub daddr_v6: [__u8; 16usize],
    pub __data: __IncompleteArrayField<::aya_ebpf::cty::c_char>,
}

